### ISSUE TITLE
The solution file is invalid!

### ISSUE THREAD

**Issue by MrFearLess98** [yashag2255/iframePCF#1]
Hi @yashag2255 

First of all thanks for sharing the Power Virtual Agent to a canvas app in Power Apps with PCF.
I have a simple problem while trying to import the Solution in PowerApps i get an error said that:
![Capture](https://user-images.githubusercontent.com/52073639/68974150-b0570c00-07f8-11ea-80a1-d7e7d0347c41.PNG)

Since i have already compressed the solution file to a zipped folder and importing them back again it keeps showing the same error message.
Any idea how to deal with this issue?

Thank you!

**Comment by yashag2255** [comment]
Hi @MrFearLess98, 

You can push this component directly using the Visual studio developer command prompt. The steps to do so are:
1. Clone the repository
2. cd into the src folder
3. Get the developer resource URL for your environment from advanced settings in Power Apps.
4. Use the command: pac auth create --url <orgurl> and authenticate with your credentials.
5. Use the command: pac pcf push --publisher-prefix contoso to push the component.

Hope this Helps!

**Comment by MrFearLess98** [comment]
Thank you it works! Keep it up!

**Comment by regreben** [comment]
Hi @yashag2255,
the "pac auth create --url" always fails with an error : 

"The resource principal named https://************.api.crm4.dynamics.com/XRMServices/2011/Organization.svc was not found in the tenant named"

Do i use the wron resource URL?

kind regards
René
