### ISSUE TITLE
pac auth create --url

### ISSUE THREAD

**Issue by regreben** [yashag2255/iframePCF#3]
Hi @yashag2255,
the "pac auth create --url" always fails with an error :

"The resource principal named https://************.api.crm4.dynamics.com/XRMServices/2011/Organization.svc was not found in the tenant named"

Do i use the wrong resource URL?

kind regards
René

**Comment by yashag2255** [comment]
The resource URL should be only until .com.

I also have updated the Managed and unmanaged solutions so that can be directly imported.
